---
- name: "install spark"
  hosts: spark
  become: yes

  tasks:
  - name: download spark
    get_url: 
      url: "https://downloads.apache.org/spark/spark-3.1.2/spark-3.1.2-bin-hadoop2.7.tgz"
      dest: /home/baurzhan87/

  - name: unarchive a file
    unarchive:
      src: /home/baurzhan87/spark-3.1.2-bin-hadoop2.7.tgz
      dest: /home/baurzhan87/
      remote_src: yes
